### ISSUE TITLE
Email preview throws error

### ISSUE THREAD

**Issue by cc-ben** [vanilla-thunder/oxid-module-devutils#15]
Hi!

On a fresh EE 6.2.2 the email preview for Order(User) and order(Owner) throws the following:

```
[2020-11-03 11:09:19] OXID Logger.ERROR: Call to a member function getRawValue() on bool ["[object] (Error(code: 0): Call to a member function getRawValue() on bool at source/tmp/smarty/cd5334d3f33da5b460f9eb32f6b6483a^%%3E^3E2^3E2C254F%%order_cust.tpl.php:394)[stacktrace]#0 vendor/smarty/smarty/libs/Smarty.class.php(1270): include()#1 vendor/oxid-esales/oxideshop-ce/source/Internal/Framework/Smarty/Legacy/LegacySmartyEngine.php(68): Smarty->fetch('email/plain/ord...')#2 vendor/oxid-esales/oxideshop-ce/source/Internal/Framework/Templating/TemplateRenderer.php(35): OxidEsales\\EshopCommunity\\Internal\\Framework\\Smarty\\Legacy\\LegacySmartyEngine->render('email/plain/ord...', Array)#3 vendor/oxid-esales/oxideshop-ce/source/Core/Email.php(594): OxidEsales\\EshopCommunity\\Internal\\Framework\\Templating\\TemplateRenderer->renderTemplate('email/plain/ord...', Array)#4 source/modules/vt/devutils/Application/Controller/DevMails.php(65): OxidEsales\\EshopCommunity\\Core\\Email->sendOrderEmailToUser(Object(VanillaThunder\\DevUtils\\Application\\Extend\\Order))#5 vendor/oxid-esales/oxideshop-ce/source/Core/Controller/BaseController.php(534): VanillaThunder\\DevUtils\\Application\\Controller\\DevMails->preview()#6 vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(347): OxidEsales\\EshopCommunity\\Core\\Controller\\BaseController->executeFunction('preview')#7 vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(280): OxidEsales\\EshopCommunity\\Core\\ShopControl->executeAction(Object(VanillaThunder\\DevUtils\\Application\\Controller\\DevMails), 'preview')#8 vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(142): OxidEsales\\EshopCommunity\\Core\\ShopControl->_process('VanillaThunder\\\\...', 'preview', NULL, NULL)#9 vendor/oxid-esales/oxideshop-ce/source/Core/Oxid.php(27): OxidEsales\\EshopCommunity\\Core\\ShopControl->start()#10 source/index.php(16): OxidEsales\\EshopCommunity\\Core\\Oxid::run()#11 {main}"] []
--

```
Any ideas about that? Would be greatfull for an advice in fixing that.

Regards
ben

**Comment by cc-ben** [comment]
Issue is solved within https://github.com/vanilla-thunder/oxid-module-devutils/wiki/Emails-Preview
